[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328new
framework = arduino
monitor_speed = 115200
upload_port = COM4

lib_deps =
  Servo
  MPU6050_tockn
  ezLED
  OneButton
build_flags = -I.

[env:unit]
platform = native
board = native_custom
build_flags = -Isrc

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -I.
lib_deps =
  ESP32Servo
  MPU6050_tockn
  ezLED
  OneButton
