[env:uno]
platform = atmelavr
board = uno
framework = arduino
monitor_speed = 115200
# To run tests on your board set `upload_port` to your COM port, e.g.:

[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
# If you know the serial port for your ESP32, set upload_port = COMx or /dev/ttyUSB0
# upload_port = COM6
# upload_port = COM3

[env:nano]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 19200
upload_port = COM6
