[platformio]
default_envs = nanoatmega328
src_dir = .

[env:nanoatmega328]
platform = atmelavr
board = nanoatmega328
framework = arduino
monitor_speed = 19200
lib_deps =
  Servo
  MPU6050_tockn
  ezLED
  OneButton
build_flags = -I.

[env:nanoatmega328_old]
platform = atmelavr
board = nanoatmega328
framework = arduino
upload_speed = 57600
monitor_speed = 19200
lib_deps =
  Servo
  MPU6050_tockn
  ezLED
  OneButton
build_flags = -I.
